include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    NF_WORKFLOW_OPTS: "--fastq test_data/ --reference test_data/ref/reference.subseq.fa.gz --threads 4"


# reminder: update AUX_IMAGE_TAG if the aux container package versions are changed
release-centrifuge:
    extends: .aux-container
    variables:
        AUX_IMAGE_NAME: "prokka"
        AUX_IMAGE_ENVFILE: "environment_prokka.yaml"
        AUX_IMAGE_TAG: "1.14.5"
