
stages:
    - build_and_run

image: ${IMAGE}


build-image:
    stage: build_and_run
    variables:
        TAG: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    before_script:
        - apk add wget openjdk11 bash
        - wget -qO- https://get.nextflow.io | bash
    script:
        - echo ${CI_BUILD_TOKEN} | docker login --username gitlab-ci-token --password-stdin ${CI_REGISTRY}
        - docker build --no-cache -t "${TAG}" -f Dockerfile .
        - docker tag "${TAG}" "${CI_PROJECT_NAME}:latest"
        - docker tag "${TAG}" "${CI_REGISTRY_IMAGE}:latest"
        # run letting nextflow orchestrate the containers
        - ./nextflow run workflow.nf \
          -w snp_calling_docker/workspace 
          -profile withdocker
          --reads test_data/subset.fa.gz --reference test_data/reference.subseq.fa.gz 
          --threads 4 --out_dir snp_calling
        # push
        - docker push "${CI_REGISTRY_IMAGE}:latest"
    artifacts:
        paths:
            # Add the output directory for the test
            - "snp_calling"
        expire_in: 1 day
