include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"


variables:
    # chunk_size here forces multiple chunks even for test data which better exercises some channels
    NF_WORKFLOW_OPTS: "--fastq test_data/fastq --reference_based_assembly --reference test_data/ref/reference.subseq.fa.gz --threads 4 --chunk_size 100000"
    NF_IGNORE_PROCESSES: "deNovo"
    CI_FLAVOUR: "new"


docker-run:
    parallel:
        matrix:
            - MATRIX_NAME: [
                "reference-based", "de-novo", "evaluate-assemblies"]
    rules:
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "reference-based"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq --reference_based_assembly --evaluate_assemblies --reference test_data/ref/reference.subseq.fa.gz --threads 4 --chunk_size 100000"
              NF_IGNORE_PROCESSES: "deNovo,assemblyStats,runProkka"
        - if: $MATRIX_NAME == "de-novo"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq --threads 4 --chunk_size 100000"
              NF_IGNORE_PROCESSES: "medakaVariant"
        - if: $MATRIX_NAME == "evaluate-assemblies"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq --threads 4 --chunk_size 100000 --evaluate_assemblies"
              NF_IGNORE_PROCESSES: "medakaVariant"


# reminder: update AUX_IMAGE_TAG if the aux container package versions are changed
release-prokka:
    extends: .aux-container
    variables:
        AUX_IMAGE_NAME: "prokka"
        AUX_IMAGE_ENVFILE: "environment_prokka.yaml"
        AUX_IMAGE_TAG: "1.14.5"
