name: bacterial-snp-nf-epi2melabs
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python ==3.8.*
    - aplanat >=0.3.3
    - fastcat
    - medaka ==1.5.0
    - pomoxis >=0.3.6
    - tensorflow ==2.2.*
    - epi2melabs
    - flye
    - dna_features_viewer
    - bcbio-gff
    - mosdepth
