name: bacterial-snp-nf-epi2melabs
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.6.*
    - aplanat>=0.2.9
    - medaka==1.2.1
    - minimap2==2.17
    - pomoxis>=0.3.6
    - racon==1.4.13
    - tensorflow==2.2.*
